apiVersion: v1
kind: Service
metadata:
  name: vlog-frontend-service
  labels:
    app: vlog-frontend
spec:
  type: LoadBalancer
  selector:
    app: vlog-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http